### ISSUE TITLE
Beaker browser find a site then lose it - Possible solution proposed

### ISSUE THREAD

**Issue by fejnartal** [beakerbrowser/beaker-core#27]
### Description
Beaker-core uses an older version of discovery-swarm with a proven bug that causes peers to not be able to reconnect after a disconnection.
This is quite noticeable in private/secrete Dat Archives with very few peers and slow/unstable connections.

### Cause:
I found this problem while working on a dat-node project.
I traced the problem down to a bug in discovery-swarm disconnection/reconnection strategy. 

When a connection problem caused a peer to disconnect from you, it was never removed from the list of active peers. Therefore, when the same peer became available and tried to reconnect it was discarded as duplicate.

### Solution
Upgrade discovery-swarm dependency to version 6.0.1 or later.

### More Context:
https://dat.discourse.group/t/why-does-beaker-find-a-site-then-lose-it/149

https://github.com/mafintosh/discovery-swarm/issues/6
https://github.com/mafintosh/discovery-swarm/pull/62

**Comment by pfrazee** [comment]
Thank you for the detailed issue and the PR. Sorry for the delayed response. Merged 👍
