### ISSUE TITLE
Experimental datPeers API does not resolve dat DNS

### ISSUE THREAD

**Issue by krismuniz** [beakerbrowser/beaker-core#3]
### Description

I've been trying out the experimental `datPeers` API and it works like a charm in regular hash dat links.

However, when trying to use the API in a regular link that is resolved via dat DNS (e.g. `dat://myurl.com/`), the API doesn't work.

When calling most of the methods of `datPeers` (e.g. `list()`, `setSessionData()`, `getSessionData()`, etc.), the console throws the following error:

```
InvalidURLError: Hostname is not a valid hash
```

### Cause

I did some digging, and found the root cause of this issue in line 76 of the `/web-apis/experimental/dat-peers.js` file: 

https://github.com/beakerbrowser/beaker-core/blob/73c76cc990494b73942452c7244271e3f6d76171/web-apis/bg/experimental/dat-peers.js#L76

The `getArchive` function makes use of the `fromUrlToKey` function:

https://github.com/beakerbrowser/beaker-core/blob/99967f940eef6f3552a863b534825480182de004/dat/library.js#L442-L445

`fromUrlToKey` does not perform a dns lookup (yet). But I assume this was on the pipeline (hence the `TODO` note)

https://github.com/beakerbrowser/beaker-core/blob/99967f940eef6f3552a863b534825480182de004/dat/library.js#L635-L638

### Potential Solution

Import `datDns` from `/dat/dns.js` file into `/dat/library.js` and incorporate into `fromUrlToKey`'s parsing logic (i.e. use `resolveName`) in order to perform a DNS lookup.

### Considerations?

Can the potential solution negatively affect how Beaker works currently? I can definitely submit a pull request to resolve this issue if it doesn't.

👋Have a nice day!

**Comment by pfrazee** [comment]
Yes! Well sleuthed, I actually detected the same bug myself (right when it was time to run our workshop at the dweb summit).

Thanks for filing. If you want to submit a PR feel free, but I'll get to it this week otherwise.

**Comment by krismuniz** [comment]
Damn that was fast! Alright, will do! 👋

**Comment by krismuniz** [comment]
Some functions that use `fromUrlToKey` are synchronous, and `datDns` isn't, so there might be cases where `fromUrlToKey` could return a `Promise` instead of a key. 

I don't see any concrete cases where returning a `Promise` might break other code since most of the times the function is passed a hash url (the only exception I've seen so far is `datPeers`, but maybe some other experimental API?). 

To avoid any conflicts with current API usage, I thought about adding an extra (optional) `resolveDns` argument to the function. The function would look like this:

```js
function fromURLToKey (url, dnsLookup = false) {
  if (Buffer.isBuffer(url)) {
    return url
  }
  if (DAT_HASH_REGEX.test(url)) {
    // simple case: given the key
    return url
  }

  var urlp = parseDatURL(url)

  // validate
  if (urlp.protocol !== 'dat:') {
    throw new InvalidURLError('URL must be a dat: scheme')
  }
  if (!DAT_HASH_REGEX.test(urlp.host)) {
    if (dnsLookup) {
      return datDns.resolveName(`dat://${urlp.host}`)
    } else {
      throw new InvalidURLError('Hostname is not a valid hash')
    }
  }

  return urlp.host
}
```

Doing so we'd make sure that the function would throw `InvalidURLError('Hostname is not a valid hash')` as expected unless we explicitly pass `dnsLookup`, which means we might expect a `Promise`. Do you think this might be necessary? Or is there a fundamental design change that should be made instead?

**Comment by pfrazee** [comment]
Hey @krismuniz sorry for the delay. I finally got around to this.

I think it was just this simple commit to fix: https://github.com/beakerbrowser/beaker/commit/e27f5bb8d52d9513e1476c650de8f7a40bb89a18

**Comment by krismuniz** [comment]
Awesome! Also, damn sneaky bug!

**Comment by pfrazee** [comment]
Ya!

**Comment by daffl** [comment]
After showing my p2p chat demo at [dat://feathers-chat.hashbase.io/](dat://feathers-chat.hashbase.io/) to a few people I still saw this happen several times when someone entered their email address (and the `experimental.datPeers` methods are called). I _think_ it only happened if Hashbase is the only peer they are connected to but can't fully confirm that yet.

It always works when [opening the hash directly](dat://5757862252cb4131892a5a88c23570ba3e013cef0ecc95344172745b8af0b6ef/).

**Comment by pfrazee** [comment]
Any chance they were on old versions of Beaker?

**Comment by daffl** [comment]
I don't think so.

![screen shot 2018-10-10 at 3 43 56 pm](https://user-images.githubusercontent.com/338316/46770212-530e9400-cca3-11e8-9c8c-184fb65badb5.png)

Should be the current one right?

**Comment by pfrazee** [comment]
Yes that's current. Hmm that's really unfortunate. Are you sure the error was `"Hostname is not a valid hash`" ?

**Comment by daffl** [comment]
Sorry, might've been a false alarm - this happened mostly on new installations and after the auto update it worked. Any reason the download page gives us an earlier version?

**Comment by pfrazee** [comment]
Sounds like a mistake on our part. Links need to get updated
